version: '3'

services:
  postgres:
    image: postgres:14
    container_name: rtllia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rtllia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rtllia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rtllia-backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rtllia
      JWT_SECRET: your_jwt_secret_key_here
      RETELL_API_KEY: your_retell_api_key_here
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - rtllia-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rtllia-frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: /api
      REACT_APP_WS_URL: ws://localhost:5000
    ports:
      - "3000:80"
    networks:
      - rtllia-network

networks:
  rtllia-network:
    driver: bridge

volumes:
  postgres_data:
