version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yourdbname
      - PGDATABASE=yourdatabase
      - PGUSER=youruser
      - PGPASSWORD=yourpassword
      - PGHOST=mongo
      - PGPORT=5432
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    depends_on:
      - mongo
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data: