version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    build:
      context: ./database
    container_name: retell-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retell_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - retell-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
    container_name: retell-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      JWT_SECRET: your_jwt_secret_key_here
      RETELL_API_KEY: YOUR_RETELL_API_KEY
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/retell_app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - retell-network
    restart: unless-stopped

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
    container_name: retell-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - retell-network
    restart: unless-stopped

networks:
  retell-network:
    driver: bridge

volumes:
  postgres_data:
  backend_uploads:
