version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    build:
      context: ./database
    container_name: retell-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retell_app
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgress:/var/lib/postgresql/data
    networks:
      - retell-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
    container_name: retell-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      JWT_SECRET: your_jwt_secret_key_here
      RETELL_API_KEY: ${RETELL_API_KEY}
      RETELL_API_BASE_URL: ${RETELL_API_BASE_URL}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/retell_app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - retell-network
    restart: unless-stopped

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
    container_name: retell-frontend
    ports:
      - "980:80"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: /api
      REACT_APP_WS_URL: ws://localhost:5000
    networks:
      - retell-network
    restart: unless-stopped

networks:
  retell-network:
    driver: bridge

volumes:
  postgres_data:
  backend_uploads:
